# generated by configure / remove this line to disable regeneration
prefix="/home/leinao/gcc-5.5"
exec_prefix="${prefix}"
bindir="${exec_prefix}/bin"
libdir="/home/leinao/DeepLearningExamples/PyTorch/LanguageModeling/BERT/train/gcc-5.5.0/objdir/isl/.libs"
datarootdir="${prefix}/share"
datadir="${datarootdir}"
sysconfdir="${prefix}/etc"
includedir="/home/leinao/DeepLearningExamples/PyTorch/LanguageModeling/BERT/train/gcc-5.5.0/objdir/isl/../../isl/include"
package="isl"
suffix=""

for option; do case "$option" in --list-all|--name) echo  "isl"
;; --help) pkg-config --help ; echo Buildscript Of "isl Library"
;; --modversion|--version) echo "0.14"
;; --requires) echo : ""
;; --libs) echo -L${libdir} "" "-lisl /home/leinao/DeepLearningExamples/PyTorch/LanguageModeling/BERT/train/gcc-5.5.0/objdir/./gmp/libgmp.la"
       :
;; --cflags) echo -I${includedir} "-I/home/leinao/DeepLearningExamples/PyTorch/LanguageModeling/BERT/train/gcc-5.5.0/objdir/gmp/../../gmp -I/home/leinao/DeepLearningExamples/PyTorch/LanguageModeling/BERT/train/gcc-5.5.0/objdir/./gmp"
       :
;; --variable=*) eval echo '$'`echo $option | sed -e 's/.*=//'`
;; --uninstalled) exit 0 
;; *) ;; esac done
